import localFont from 'next/font/local'
import "./globals.css";
import Link from 'next/link';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const myFont = localFont({ src:'../../public/Acorn-Bold.woff2' });

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${myFont.className} scroll-auto`}>
      <body className='bg-gradient-to-br from-cyan-400 via-blue-500 to-indigo-600 min-h-screen flex justify-center flex-wrap'>
        <header className='h-14 w-xl flex backdrop-blur-lg bg-white/20 border mx-auto mt-8
      border-white/30 rounded-full justify-center items-center gap-3 fixed text-white text-xl tracking-wide z-50'>
          <Link href='/' className='mx-3'>Home</Link>
          <Link href='/' className='mx-3'>About</Link>
          <Link href='/' className='mx-3'>Work</Link>
          <Link href='/' className='mx-3'>Notes</Link>
          <Link href='/' className='mx-3'>Contact</Link>
        </header>
        {children}
        <footer className='flex flex-wrap justify-center w-screen text-2xl mb-24 gap-8'>
          <div className='basis-[64rem] min-h-8 text-left text-white'>
            <p className='text-emerald-500'>© 2025 Korz dev</p>
          </div>
          <div className='basis-[16rem] min-h-8 text-white'>
            <p className='text-emerald-500 mb-4'>Elsewhere</p>
            <ul className='list-none'>
              <li><a href='#'>ArtStation</a></li>
              <li><a href='#'>Instagram</a></li>
              <li><a href='#'>GitHub</a></li>
              <li><a href='#'>VK</a></li>
            </ul>
          </div>
          <div className='basis-[16rem] min-h-8 text-white'>
            <p className='text-emerald-500 mb-4'>Contact</p>
            <ul className='list-none'>
              <li>
                <a href='#'>
                  Email
                </a>
              </li>
            </ul>
          </div>
        </footer>
      </body>
    </html>
  );
}
